## récupération des commentaires du site dummyjson

In [90]:
import requests

# URL pour récupérer tous les commentaires
url = "https://dummyjson.com/comments?limit=0"

# Envoi de la requête GET
response = requests.get(url)

if response.status_code == 200:
    data = response.json()
    comments = data["comments"]
else:
    print("Erreur lors de la récupération des commentaires :", response.status_code)

### Vérification de la taille des commentaires

In [91]:
len(comments)

340

### Visualisation  des commentaires

In [92]:
import pandas as pd

comments_df = pd.DataFrame(comments)

comments_df.head()

,id,body,postId,user
0,1,This is some awesome thinking!,100,"{'id': 63, 'username': 'eburras1q'}"
1,2,What terrific math skills you’re showing!,27,"{'id': 71, 'username': 'omarsland1y'}"
2,3,You are an amazing writer!,61,"{'id': 29, 'username': 'jissetts'}"
3,4,Wow! You have improved so much!,8,"{'id': 19, 'username': 'bleveragei'}"
4,5,Nice idea!,62,"{'id': 70, 'username': 'cmasurel1x'}"

### Restructuration du DataFrame

In [93]:
comments_df['user_id'] = comments_df['user'].apply(lambda x: x['id'])
comments_df['username'] = comments_df['user'].apply(lambda x: x['username'])

comments_df.drop(columns=['user'], inplace=True)

In [94]:
comments_df.tail()

,id,body,postId,user_id,username
335,336,"I checked the clouds during midnight, and wond...",73,91,hyaknov2i
336,337,"This is such an Insta beauty, why waste it by ...",79,77,rkingswood24
337,338,Have we met before? If not – would you like to...,91,31,smargiottau
338,339,"With great pictures, comes great responsibility.",4,89,cdwyr2g
339,340,I could say this is one of the greatest pic of...,71,86,whuman2d

In [95]:
comments_df.to_csv('comments_df.csv', index=False)

In [96]:
import pandas as pd
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
comments_df = pd.read_csv('comments_df.csv')

In [97]:
comments_df.tail()

,id,body,postId,user_id,username
335,336,"I checked the clouds during midnight, and wond...",73,91,hyaknov2i
336,337,"This is such an Insta beauty, why waste it by ...",79,77,rkingswood24
337,338,Have we met before? If not – would you like to...,91,31,smargiottau
338,339,"With great pictures, comes great responsibility.",4,89,cdwyr2g
339,340,I could say this is one of the greatest pic of...,71,86,whuman2d

## Nettoyer les commentaires

In [98]:



# Fonction pour nettoyer les phrases
def clean_text(text):
    # Supprimer les caractères spéciaux, les liens et les emojis
    text = re.sub(r'http\S+', '', text)  # Supprimer les liens
    text = re.sub(r'[^\w\s]', '', text)  # Supprimer les caractères spéciaux
    text = text.encode('ascii', 'ignore').decode('ascii')  # Supprimer les emojis
    return text

# Appliquer le nettoyage à la colonne 'text'
comments_df['clean_text'] = comments_df['body'].apply(clean_text)
comments_df

,id,body,postId,user_id,username,clean_text
0,1,This is some awesome thinking!,100,63,eburras1q,This is some awesome thinking
1,2,What terrific math skills you’re showing!,27,71,omarsland1y,What terrific math skills youre showing
2,3,You are an amazing writer!,61,29,jissetts,You are an amazing writer
3,4,Wow! You have improved so much!,8,19,bleveragei,Wow You have improved so much
4,5,Nice idea!,62,70,cmasurel1x,Nice idea
...,...,...,...,...,...,...
335,336,"I checked the clouds during midnight, and wond...",73,91,hyaknov2i,I checked the clouds during midnight and wonde...
336,337,"This is such an Insta beauty, why waste it by ...",79,77,rkingswood24,This is such an Insta beauty why waste it by c...
337,338,Have we met before? If not – would you like to...,91,31,smargiottau,Have we met before If not would you like to g...
338,339,"With great pictures, comes great responsibility.",4,89,cdwyr2g,With great pictures comes great responsibility
339,340,I could say this is one of the greatest pic of...,71,86,whuman2d,I could say this is one of the greatest pic of...

### Charger le modèle Detoxify

In [99]:
from detoxify import Detoxify
model = Detoxify('original')

### Faire l’analyse des toxicités de ces commentaires avec le modèle detoxify

In [100]:
toxicity_scores = []
for text in comments_df['clean_text']:
    result = model.predict(text)
    toxicity_scores.append(result)

comments_df['toxicity_score'] = toxicity_scores

comments_df

,id,body,postId,user_id,username,clean_text,toxicity_score
0,1,This is some awesome thinking!,100,63,eburras1q,This is some awesome thinking,"{'toxicity': 0.0007598002, 'severe_toxicity': ..."
1,2,What terrific math skills you’re showing!,27,71,omarsland1y,What terrific math skills youre showing,"{'toxicity': 0.0074881366, 'severe_toxicity': ..."
2,3,You are an amazing writer!,61,29,jissetts,You are an amazing writer,"{'toxicity': 0.00063423335, 'severe_toxicity':..."
3,4,Wow! You have improved so much!,8,19,bleveragei,Wow You have improved so much,"{'toxicity': 0.00094851875, 'severe_toxicity':..."
4,5,Nice idea!,62,70,cmasurel1x,Nice idea,"{'toxicity': 0.00065386726, 'severe_toxicity':..."
...,...,...,...,...,...,...,...
335,336,"I checked the clouds during midnight, and wond...",73,91,hyaknov2i,I checked the clouds during midnight and wonde...,"{'toxicity': 0.0006925876, 'severe_toxicity': ..."
336,337,"This is such an Insta beauty, why waste it by ...",79,77,rkingswood24,This is such an Insta beauty why waste it by c...,"{'toxicity': 0.013269149, 'severe_toxicity': 0..."
337,338,Have we met before? If not – would you like to...,91,31,smargiottau,Have we met before If not would you like to g...,"{'toxicity': 0.0008845267, 'severe_toxicity': ..."
338,339,"With great pictures, comes great responsibility.",4,89,cdwyr2g,With great pictures comes great responsibility,"{'toxicity': 0.00060104684, 'severe_toxicity':..."
339,340,I could say this is one of the greatest pic of...,71,86,whuman2d,I could say this is one of the greatest pic of...,"{'toxicity': 0.0730733, 'severe_toxicity': 0.0..."

### Restructuration du DataFrame

In [101]:
comments_df['toxicity'] = comments_df['toxicity_score'].apply(lambda x: x['toxicity'])
comments_df['severe_toxicity'] = comments_df['toxicity_score'].apply(lambda x: x['severe_toxicity'])
comments_df['obscene'] = comments_df['toxicity_score'].apply(lambda x: x['obscene'])
comments_df['threat'] = comments_df['toxicity_score'].apply(lambda x: x['threat'])
comments_df['insult'] = comments_df['toxicity_score'].apply(lambda x: x['insult'])
comments_df['identity_attack'] = comments_df['toxicity_score'].apply(lambda x: x['identity_attack'])



comments_df.drop(columns=['toxicity_score'], inplace=True)

In [88]:
comments_df

,id,body,postId,user_id,username,clean_text,toxicity,severe_toxicity,obscene,threat,insult,identity_attack
0,1,This is some awesome thinking!,100,63,eburras1q,This is some awesome thinking,0.000760,0.000112,0.000195,0.000110,0.000170,0.000133
1,2,What terrific math skills you’re showing!,27,71,omarsland1y,What terrific math skills youre showing,0.007488,0.000083,0.000288,0.000123,0.000430,0.000199
2,3,You are an amazing writer!,61,29,jissetts,You are an amazing writer,0.000634,0.000124,0.000188,0.000135,0.000175,0.000137
3,4,Wow! You have improved so much!,8,19,bleveragei,Wow You have improved so much,0.000949,0.000105,0.000170,0.000125,0.000191,0.000140
4,5,Nice idea!,62,70,cmasurel1x,Nice idea,0.000654,0.000117,0.000187,0.000113,0.000176,0.000137
...,...,...,...,...,...,...,...,...,...,...,...,...
335,336,"I checked the clouds during midnight, and wond...",73,91,hyaknov2i,I checked the clouds during midnight and wonde...,0.000693,0.000113,0.000174,0.000123,0.000173,0.000137
336,337,"This is such an Insta beauty, why waste it by ...",79,77,rkingswood24,This is such an Insta beauty why waste it by c...,0.013269,0.000100,0.000508,0.000147,0.000501,0.000240
337,338,Have we met before? If not – would you like to...,91,31,smargiottau,Have we met before If not would you like to g...,0.000885,0.000108,0.000166,0.000121,0.000177,0.000149
338,339,"With great pictures, comes great responsibility.",4,89,cdwyr2g,With great pictures comes great responsibility,0.000601,0.000125,0.000179,0.000132,0.000175,0.000142
339,340,I could say this is one of the greatest pic of...,71,86,whuman2d,I could say this is one of the greatest pic of...,0.073073,0.000175,0.003829,0.000411,0.002350,0.000365

## Charger les données dans MongoDB

In [102]:
import pymongo

mongo_client = pymongo.MongoClient("mongodb://localhost:27017/")
mongo_db = mongo_client["dummyjson"]
mongo_collection = mongo_db["commentaires"]
comment_docs = comments_df.to_dict(orient='records')
mongo_collection.insert_many(comment_docs)

InsertManyResult([ObjectId('6613f2701fbbc780957eb7b9'), ObjectId('6613f2701fbbc780957eb7ba'), ObjectId('6613f2701fbbc780957eb7bb'), ObjectId('6613f2701fbbc780957eb7bc'), ObjectId('6613f2701fbbc780957eb7bd'), ObjectId('6613f2701fbbc780957eb7be'), ObjectId('6613f2701fbbc780957eb7bf'), ObjectId('6613f2701fbbc780957eb7c0'), ObjectId('6613f2701fbbc780957eb7c1'), ObjectId('6613f2701fbbc780957eb7c2'), ObjectId('6613f2701fbbc780957eb7c3'), ObjectId('6613f2701fbbc780957eb7c4'), ObjectId('6613f2701fbbc780957eb7c5'), ObjectId('6613f2701fbbc780957eb7c6'), ObjectId('6613f2701fbbc780957eb7c7'), ObjectId('6613f2701fbbc780957eb7c8'), ObjectId('6613f2701fbbc780957eb7c9'), ObjectId('6613f2701fbbc780957eb7ca'), ObjectId('6613f2701fbbc780957eb7cb'), ObjectId('6613f2701fbbc780957eb7cc'), ObjectId('6613f2701fbbc780957eb7cd'), ObjectId('6613f2701fbbc780957eb7ce'), ObjectId('6613f2701fbbc780957eb7cf'), ObjectId('6613f2701fbbc780957eb7d0'), ObjectId('6613f2701fbbc780957eb7d1'), ObjectId('6613f2701fbbc780957eb7d2'), ObjectId('6613f2701fbbc780957eb7d3'), ObjectId('6613f2701fbbc780957eb7d4'), ObjectId('6613f2701fbbc780957eb7d5'), ObjectId('6613f2701fbbc780957eb7d6'), ObjectId('6613f2701fbbc780957eb7d7'), ObjectId('6613f2701fbbc780957eb7d8'), ObjectId('6613f2701fbbc780957eb7d9'), ObjectId('6613f2701fbbc780957eb7da'), ObjectId('6613f2701fbbc780957eb7db'), ObjectId('6613f2701fbbc780957eb7dc'), ObjectId('6613f2701fbbc780957eb7dd'), ObjectId('6613f2701fbbc780957eb7de'), ObjectId('6613f2701fbbc780957eb7df'), ObjectId('6613f2701fbbc780957eb7e0'), ObjectId('6613f2701fbbc780957eb7e1'), ObjectId('6613f2701fbbc780957eb7e2'), ObjectId('6613f2701fbbc780957eb7e3'), ObjectId('6613f2701fbbc780957eb7e4'), ObjectId('6613f2701fbbc780957eb7e5'), ObjectId('6613f2701fbbc780957eb7e6'), ObjectId('6613f2701fbbc780957eb7e7'), ObjectId('6613f2701fbbc780957eb7e8'), ObjectId('6613f2701fbbc780957eb7e9'), ObjectId('6613f2701fbbc780957eb7ea'), ObjectId('6613f2701fbbc780957eb7eb'), ObjectId('6613f2701fbbc780957eb7ec'), ObjectId('6613f2701fbbc780957eb7ed'), ObjectId('6613f2701fbbc780957eb7ee'), ObjectId('6613f2701fbbc780957eb7ef'), ObjectId('6613f2701fbbc780957eb7f0'), ObjectId('6613f2701fbbc780957eb7f1'), ObjectId('6613f2701fbbc780957eb7f2'), ObjectId('6613f2701fbbc780957eb7f3'), ObjectId('6613f2701fbbc780957eb7f4'), ObjectId('6613f2701fbbc780957eb7f5'), ObjectId('6613f2701fbbc780957eb7f6'), ObjectId('6613f2701fbbc780957eb7f7'), ObjectId('6613f2701fbbc780957eb7f8'), ObjectId('6613f2701fbbc780957eb7f9'), ObjectId('6613f2701fbbc780957eb7fa'), ObjectId('6613f2701fbbc780957eb7fb'), ObjectId('6613f2701fbbc780957eb7fc'), ObjectId('6613f2701fbbc780957eb7fd'), ObjectId('6613f2701fbbc780957eb7fe'), ObjectId('6613f2701fbbc780957eb7ff'), ObjectId('6613f2701fbbc780957eb800'), ObjectId('6613f2701fbbc780957eb801'), ObjectId('6613f2701fbbc780957eb802'), ObjectId('6613f2701fbbc780957eb803'), ObjectId('6613f2701fbbc780957eb804'), ObjectId('6613f2701fbbc780957eb805'), ObjectId('6613f2701fbbc780957eb806'), ObjectId('6613f2701fbbc780957eb807'), ObjectId('6613f2701fbbc780957eb808'), ObjectId('6613f2701fbbc780957eb809'), ObjectId('6613f2701fbbc780957eb80a'), ObjectId('6613f2701fbbc780957eb80b'), ObjectId('6613f2701fbbc780957eb80c'), ObjectId('6613f2701fbbc780957eb80d'), ObjectId('6613f2701fbbc780957eb80e'), ObjectId('6613f2701fbbc780957eb80f'), ObjectId('6613f2701fbbc780957eb810'), ObjectId('6613f2701fbbc780957eb811'), ObjectId('6613f2701fbbc780957eb812'), ObjectId('6613f2701fbbc780957eb813'), ObjectId('6613f2701fbbc780957eb814'), ObjectId('6613f2701fbbc780957eb815'), ObjectId('6613f2701fbbc780957eb816'), ObjectId('6613f2701fbbc780957eb817'), ObjectId('6613f2701fbbc780957eb818'), ObjectId('6613f2701fbbc780957eb819'), ObjectId('6613f2701fbbc780957eb81a'), ObjectId('6613f2701fbbc780957eb81b'), ObjectId('6613f2701fbbc780957eb81c'), ObjectId('6613f2701fbbc780957eb81d'), ObjectId('6613f2701fbbc780957eb81e'), ObjectId('6613f2701fbbc780957eb81f'), ObjectId('6613f2701fbbc780957eb820'), ObjectId('6613f2701fbbc780957eb821'), ObjectId('6613f2701fbbc780957eb822'), ObjectId('6613f2701fbbc780957eb823'), ObjectId('6613f2701fbbc780957eb824'), ObjectId('6613f2701fbbc780957eb825'), ObjectId('6613f2701fbbc780957eb826'), ObjectId('6613f2701fbbc780957eb827'), ObjectId('6613f2701fbbc780957eb828'), ObjectId('6613f2701fbbc780957eb829'), ObjectId('6613f2701fbbc780957eb82a'), ObjectId('6613f2701fbbc780957eb82b'), ObjectId('6613f2701fbbc780957eb82c'), ObjectId('6613f2701fbbc780957eb82d'), ObjectId('6613f2701fbbc780957eb82e'), ObjectId('6613f2701fbbc780957eb82f'), ObjectId('6613f2701fbbc780957eb830'), ObjectId('6613f2701fbbc780957eb831'), ObjectId('6613f2701fbbc780957eb832'), ObjectId('6613f2701fbbc780957eb833'), ObjectId('6613f2701fbbc780957eb834'), ObjectId('6613f2701fbbc780957eb835'), ObjectId('6613f2701fbbc780957eb836'), ObjectId('6613f2701fbbc780957eb837'), ObjectId('6613f2701fbbc780957eb838'), ObjectId('6613f2701fbbc780957eb839'), ObjectId('6613f2701fbbc780957eb83a'), ObjectId('6613f2701fbbc780957eb83b'), ObjectId('6613f2701fbbc780957eb83c'), ObjectId('6613f2701fbbc780957eb83d'), ObjectId('6613f2701fbbc780957eb83e'), ObjectId('6613f2701fbbc780957eb83f'), ObjectId('6613f2701fbbc780957eb840'), ObjectId('6613f2701fbbc780957eb841'), ObjectId('6613f2701fbbc780957eb842'), ObjectId('6613f2701fbbc780957eb843'), ObjectId('6613f2701fbbc780957eb844'), ObjectId('6613f2701fbbc780957eb845'), ObjectId('6613f2701fbbc780957eb846'), ObjectId('6613f2701fbbc780957eb847'), ObjectId('6613f2701fbbc780957eb848'), ObjectId('6613f2701fbbc780957eb849'), ObjectId('6613f2701fbbc780957eb84a'), ObjectId('6613f2701fbbc780957eb84b'), ObjectId('6613f2701fbbc780957eb84c'), ObjectId('6613f2701fbbc780957eb84d'), ObjectId('6613f2701fbbc780957eb84e'), ObjectId('6613f2701fbbc780957eb84f'), ObjectId('6613f2701fbbc780957eb850'), ObjectId('6613f2701fbbc780957eb851'), ObjectId('6613f2701fbbc780957eb852'), ObjectId('6613f2701fbbc780957eb853'), ObjectId('6613f2701fbbc780957eb854'), ObjectId('6613f2701fbbc780957eb855'), ObjectId('6613f2701fbbc780957eb856'), ObjectId('6613f2701fbbc780957eb857'), ObjectId('6613f2701fbbc780957eb858'), ObjectId('6613f2701fbbc780957eb859'), ObjectId('6613f2701fbbc780957eb85a'), ObjectId('6613f2701fbbc780957eb85b'), ObjectId('6613f2701fbbc780957eb85c'), ObjectId('6613f2701fbbc780957eb85d'), ObjectId('6613f2701fbbc780957eb85e'), ObjectId('6613f2701fbbc780957eb85f'), ObjectId('6613f2701fbbc780957eb860'), ObjectId('6613f2701fbbc780957eb861'), ObjectId('6613f2701fbbc780957eb862'), ObjectId('6613f2701fbbc780957eb863'), ObjectId('6613f2701fbbc780957eb864'), ObjectId('6613f2701fbbc780957eb865'), ObjectId('6613f2701fbbc780957eb866'), ObjectId('6613f2701fbbc780957eb867'), ObjectId('6613f2701fbbc780957eb868'), ObjectId('6613f2701fbbc780957eb869'), ObjectId('6613f2701fbbc780957eb86a'), ObjectId('6613f2701fbbc780957eb86b'), ObjectId('6613f2701fbbc780957eb86c'), ObjectId('6613f2701fbbc780957eb86d'), ObjectId('6613f2701fbbc780957eb86e'), ObjectId('6613f2701fbbc780957eb86f'), ObjectId('6613f2701fbbc780957eb870'), ObjectId('6613f2701fbbc780957eb871'), ObjectId('6613f2701fbbc780957eb872'), ObjectId('6613f2701fbbc780957eb873'), ObjectId('6613f2701fbbc780957eb874'), ObjectId('6613f2701fbbc780957eb875'), ObjectId('6613f2701fbbc780957eb876'), ObjectId('6613f2701fbbc780957eb877'), ObjectId('6613f2701fbbc780957eb878'), ObjectId('6613f2701fbbc780957eb879'), ObjectId('6613f2701fbbc780957eb87a'), ObjectId('6613f2701fbbc780957eb87b'), ObjectId('6613f2701fbbc780957eb87c'), ObjectId('6613f2701fbbc780957eb87d'), ObjectId('6613f2701fbbc780957eb87e'), ObjectId('6613f2701fbbc780957eb87f'), ObjectId('6613f2701fbbc780957eb880'), ObjectId('6613f2701fbbc780957eb881'), ObjectId('6613f2701fbbc780957eb882'), ObjectId('6613f2701fbbc780957eb883'), ObjectId('6613f2701fbbc780957eb884'), ObjectId('6613f2701fbbc780957eb885'), ObjectId('6613f2701fbbc780957eb886'), ObjectId('6613f2701fbbc780957eb887'), ObjectId('6613f2701fbbc780957eb888'), ObjectId('6613f2701fbbc780957eb889'), ObjectId('6613f2701fbbc780957eb88a'), ObjectId('6613f2701fbbc780957eb88b'), ObjectId('6613f2701fbbc780957eb88c'), ObjectId('6613f2701fbbc780957eb88d'), ObjectId('6613f2701fbbc780957eb88e'), ObjectId('6613f2701fbbc780957eb88f'), ObjectId('6613f2701fbbc780957eb890'), ObjectId('6613f2701fbbc780957eb891'), ObjectId('6613f2701fbbc780957eb892'), ObjectId('6613f2701fbbc780957eb893'), ObjectId('6613f2701fbbc780957eb894'), ObjectId('6613f2701fbbc780957eb895'), ObjectId('6613f2701fbbc780957eb896'), ObjectId('6613f2701fbbc780957eb897'), ObjectId('6613f2701fbbc780957eb898'), ObjectId('6613f2701fbbc780957eb899'), ObjectId('6613f2701fbbc780957eb89a'), ObjectId('6613f2701fbbc780957eb89b'), ObjectId('6613f2701fbbc780957eb89c'), ObjectId('6613f2701fbbc780957eb89d'), ObjectId('6613f2701fbbc780957eb89e'), ObjectId('6613f2701fbbc780957eb89f'), ObjectId('6613f2701fbbc780957eb8a0'), ObjectId('6613f2701fbbc780957eb8a1'), ObjectId('6613f2701fbbc780957eb8a2'), ObjectId('6613f2701fbbc780957eb8a3'), ObjectId('6613f2701fbbc780957eb8a4'), ObjectId('6613f2701fbbc780957eb8a5'), ObjectId('6613f2701fbbc780957eb8a6'), ObjectId('6613f2701fbbc780957eb8a7'), ObjectId('6613f2701fbbc780957eb8a8'), ObjectId('6613f2701fbbc780957eb8a9'), ObjectId('6613f2701fbbc780957eb8aa'), ObjectId('6613f2701fbbc780957eb8ab'), ObjectId('6613f2701fbbc780957eb8ac'), ObjectId('6613f2701fbbc780957eb8ad'), ObjectId('6613f2701fbbc780957eb8ae'), ObjectId('6613f2701fbbc780957eb8af'), ObjectId('6613f2701fbbc780957eb8b0'), ObjectId('6613f2701fbbc780957eb8b1'), ObjectId('6613f2701fbbc780957eb8b2'), ObjectId('6613f2701fbbc780957eb8b3'), ObjectId('6613f2701fbbc780957eb8b4'), ObjectId('6613f2701fbbc780957eb8b5'), ObjectId('6613f2701fbbc780957eb8b6'), ObjectId('6613f2701fbbc780957eb8b7'), ObjectId('6613f2701fbbc780957eb8b8'), ObjectId('6613f2701fbbc780957eb8b9'), ObjectId('6613f2701fbbc780957eb8ba'), ObjectId('6613f2701fbbc780957eb8bb'), ObjectId('6613f2701fbbc780957eb8bc'), ObjectId('6613f2701fbbc780957eb8bd'), ObjectId('6613f2701fbbc780957eb8be'), ObjectId('6613f2701fbbc780957eb8bf'), ObjectId('6613f2701fbbc780957eb8c0'), ObjectId('6613f2701fbbc780957eb8c1'), ObjectId('6613f2701fbbc780957eb8c2'), ObjectId('6613f2701fbbc780957eb8c3'), ObjectId('6613f2701fbbc780957eb8c4'), ObjectId('6613f2701fbbc780957eb8c5'), ObjectId('6613f2701fbbc780957eb8c6'), ObjectId('6613f2701fbbc780957eb8c7'), ObjectId('6613f2701fbbc780957eb8c8'), ObjectId('6613f2701fbbc780957eb8c9'), ObjectId('6613f2701fbbc780957eb8ca'), ObjectId('6613f2701fbbc780957eb8cb'), ObjectId('6613f2701fbbc780957eb8cc'), ObjectId('6613f2701fbbc780957eb8cd'), ObjectId('6613f2701fbbc780957eb8ce'), ObjectId('6613f2701fbbc780957eb8cf'), ObjectId('6613f2701fbbc780957eb8d0'), ObjectId('6613f2701fbbc780957eb8d1'), ObjectId('6613f2701fbbc780957eb8d2'), ObjectId('6613f2701fbbc780957eb8d3'), ObjectId('6613f2701fbbc780957eb8d4'), ObjectId('6613f2701fbbc780957eb8d5'), ObjectId('6613f2701fbbc780957eb8d6'), ObjectId('6613f2701fbbc780957eb8d7'), ObjectId('6613f2701fbbc780957eb8d8'), ObjectId('6613f2701fbbc780957eb8d9'), ObjectId('6613f2701fbbc780957eb8da'), ObjectId('6613f2701fbbc780957eb8db'), ObjectId('6613f2701fbbc780957eb8dc'), ObjectId('6613f2701fbbc780957eb8dd'), ObjectId('6613f2701fbbc780957eb8de'), ObjectId('6613f2701fbbc780957eb8df'), ObjectId('6613f2701fbbc780957eb8e0'), ObjectId('6613f2701fbbc780957eb8e1'), ObjectId('6613f2701fbbc780957eb8e2'), ObjectId('6613f2701fbbc780957eb8e3'), ObjectId('6613f2701fbbc780957eb8e4'), ObjectId('6613f2701fbbc780957eb8e5'), ObjectId('6613f2701fbbc780957eb8e6'), ObjectId('6613f2701fbbc780957eb8e7'), ObjectId('6613f2701fbbc780957eb8e8'), ObjectId('6613f2701fbbc780957eb8e9'), ObjectId('6613f2701fbbc780957eb8ea'), ObjectId('6613f2701fbbc780957eb8eb'), ObjectId('6613f2701fbbc780957eb8ec'), ObjectId('6613f2701fbbc780957eb8ed'), ObjectId('6613f2701fbbc780957eb8ee'), ObjectId('6613f2701fbbc780957eb8ef'), ObjectId('6613f2701fbbc780957eb8f0'), ObjectId('6613f2701fbbc780957eb8f1'), ObjectId('6613f2701fbbc780957eb8f2'), ObjectId('6613f2701fbbc780957eb8f3'), ObjectId('6613f2701fbbc780957eb8f4'), ObjectId('6613f2701fbbc780957eb8f5'), ObjectId('6613f2701fbbc780957eb8f6'), ObjectId('6613f2701fbbc780957eb8f7'), ObjectId('6613f2701fbbc780957eb8f8'), ObjectId('6613f2701fbbc780957eb8f9'), ObjectId('6613f2701fbbc780957eb8fa'), ObjectId('6613f2701fbbc780957eb8fb'), ObjectId('6613f2701fbbc780957eb8fc'), ObjectId('6613f2701fbbc780957eb8fd'), ObjectId('6613f2701fbbc780957eb8fe'), ObjectId('6613f2701fbbc780957eb8ff'), ObjectId('6613f2701fbbc780957eb900'), ObjectId('6613f2701fbbc780957eb901'), ObjectId('6613f2701fbbc780957eb902'), ObjectId('6613f2701fbbc780957eb903'), ObjectId('6613f2701fbbc780957eb904'), ObjectId('6613f2701fbbc780957eb905'), ObjectId('6613f2701fbbc780957eb906'), ObjectId('6613f2701fbbc780957eb907'), ObjectId('6613f2701fbbc780957eb908'), ObjectId('6613f2701fbbc780957eb909'), ObjectId('6613f2701fbbc780957eb90a'), ObjectId('6613f2701fbbc780957eb90b'), ObjectId('6613f2701fbbc780957eb90c')], acknowledged=True)